[package]
name = "scu"
version = "1.1.1"
edition = "2021"

[profile.release]
strip = true
lto = true

[dependencies]
regex = { version = "1", default-features = false, features = ["unicode-perl", "std"] }
