[package]
name = "scu"
version = "1.0.0"
edition = "2021"

[profile.release]
strip = true
lto = true
debug = false
panic = "abort"
codegen-units = 1
opt-level = "z"

[dependencies]
regex = { version = "1", default-features = false, features = ["unicode-perl", "std"] }
